# FISCO BCOS v3.x Java SDK Configuration Template (config-example.toml)

# =============================================================
#                   加密和证书配置 (Crypto Material)
# =============================================================
[cryptoMaterial]
# 是否使用国密加密 (SM Crypto)
# true: 使用国密 (SM2/SM3/SM4)
# false: 使用标准加密 (ECDSA/SHA3/Secp256k1)
useSMCrypto = "false"

# 证书路径配置 (用于节点间以及SDK与节点间的SSL/TLS安全连接)
# 这些路径可以是绝对路径，也可以是相对于 classpath 的路径
# 如果 useSMCrypto = false (标准加密)
caCertPath = "conf/ca.crt"             # CA 根证书
sdkCertPath = "conf/sdk.crt"           # SDK 证书
sdkPrivateKeyPath = "conf/sdk.key"     # SDK 私钥

# 如果 useSMCrypto = true (国密加密)
# 国密 CA 根证书、SDK 证书、SDK 私钥、加密 SDK 证书、加密 SDK 私钥
# smCaCertPath = "conf/sm_ca.crt"
# smSdkCertPath = "conf/sm_sdk.crt"
# smSdkPrivateKeyPath = "conf/sm_sdk.key"
# smEnSdkCertPath = "conf/sm_ensdk.crt"
# smEnSdkPrivateKeyPath = "conf/sm_ensdk.key"

# =============================================================
#                         网络配置 (Network)
# =============================================================
[network]
# 配置 SDK 可以连接的节点列表 (IP:Port 格式)
# SDK 会尝试连接这些节点以获取指定群组的信息和进行交互
# 至少需要配置一个您要交互的群组中的节点
peers = ["192.168.0.102:20200", "192.168.0.102:20201"] # !!! 修改为您的节点 IP 和 RPC 端口 !!!
defaultGroup="group0"
# 网络消息通信超时时间 (毫秒)
messageTimeout = "10000"

# 是否启用 JNI Channel (通常保持 false，除非有特殊性能需求且环境支持)
# useJni = false

# =============================================================
#                         链配置 (Chain)
# =============================================================
[chain]
# 链 ID (必须与您连接的 FISCO BCOS 链的 ChainID 一致)
#chainId = "0"  # !!! 修改为您的链 ID !!!